name: CI/CD
env:
  CONT_NAME: "task"
  
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t ${{ env.CONT_NAME }}:${{ github.sha }} .
    - name: Install yc cli
      run: sudo curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash; yc init
