name: CI/CD
env:
  CONT_NAME: "task"
  
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t cr.yandex/${{ secrets.YCDOCKERID }}/${{ env.CONT_NAME }}:${{ github.sha }} .
    - name: Install yc cli
      run: curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i /opt/yc -n
    - name: docker auth
      run:  docker login --username oauth --password ${{ secrets.YCCLI }} cr.yandex
    - name: Push docker image
      run:  /opt/yc/bin/yc container registry configure-docker; docker push cr.yandex/${{ secrets.YCDOCKERID }}/task:${{ github.sha }}
    - name: Prepare ssh key
      run: touch id_rsa; echo '${{ secrets.PRISSH }}' > id_rsa
    - name: Connect to VM
      run: ssh ${{ secrets.SSHINFO }} -i id_rsa

    
