name: CI/CD
env:
  CONT_NAME: "task"
  
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t cr.yandex/${{ secrets.YCDOCKERID }}/${{ env.CONT_NAME }}:${{ github.sha }} .
    - name: Install yc cli
      run: curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i /opt/yc -n
    - name: yc auth
      run:  /opt/yc/bin/yc config set token ${{ secrets.YCCLI }}; /opt/yc/bin/yc config profile create tajogi; \
            /opt/yc/bin/yc container registry add-access-binding ${{ secrets.YCDOCKERID }} --role container-registry.admin --subject userAccount:ajeh6pcfg7hrsa90t0jn
    - name: Push docker image
      run:  /opt/yc/bin/yc container registry configure-docker; docker push cr.yandex/${{ secrets.YCDOCKERID }}/${{ env.CONT_NAME }}:${{ github.sha }}
    
