name: CI/CD

on:
  push:
    branches:
      - "main"
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build container 
        run: |
          using: 'docker'
          image: 'Dockerfile'
      - name: Push container
      
          
        
        

