name: CI/CA
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
       containername: task:$(date +%s)
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t $containername . 
