name: CI/CD
env:
  CONT_NAME: "task"
  
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t cr.yandex/${{ secrets.YCDOCKERID }}/${{ env.CONT_NAME }}:${{ github.sha }} .
    - name: Install yc cli
      run: curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i /opt/yc -n
    - name: docker auth
      run:  docker login --username oauth --password ${{ secrets.YCCLI }} cr.yandex
    - name: Push docker image
      run:  /opt/yc/bin/yc container registry configure-docker; docker push cr.yandex/${{ secrets.YCDOCKERID }}/task:${{ github.sha }}
    - name: Run container
      run: /opt/yc/bin/yc config set instance-service-account true; /opt/yc/bin/yc  compute instance create --name first-instance --zone ru-central1-a --network-interface subnet-name=default-ru-central1-a,nat-ip-version=ipv4 --create-boot-disk image-folder-id=standard-images,image-family=ubuntu-1604-lts --ssh-key ${{ secrets.PUBSSH }}

    
